# Created using wingetcreate 0.3.0.3
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: Apple.BonjourPrintServices
PackageVersion: 2.0.2.0
PackageLocale: en-US
Publisher: Apple Inc.
PackageName: Bonjour Printer Services
License: © Apple Inc. All Rights Reserved.
ShortDescription: Bonjour Printer Services
ManifestType: defaultLocale
ManifestVersion: 1.0.0

